"""
Durable order-approval workflow.

  step: save order PENDING           → DynamoDB
  create_callback + step: email approve/reject links (carrying the callback id) via SES
  callback.result()                  → SUSPENDS here, no compute, until someone decides
  step: update order APPROVED/REJECTED → DynamoDB

Replay-safety: every side effect (DynamoDB, SES) is inside a @durable_step, and the
order_id is generated by the starter (outside this handler) — never in replayed code.
"""
import os
import json

import boto3
from aws_durable_execution_sdk_python import (
    DurableContext, StepContext, durable_execution, durable_step,
)
from aws_durable_execution_sdk_python.config import Duration, CallbackConfig

TABLE = os.environ["ORDERS_TABLE"]
SENDER = os.environ["SENDER_EMAIL"]
APPROVE_URL = os.environ.get("APPROVE_URL", "")

ddb = boto3.resource("dynamodb")
ses = boto3.client("ses")


@durable_step
def save_pending(ctx: StepContext, order: dict) -> dict:
    ddb.Table(TABLE).put_item(Item={**order, "status": "PENDING_APPROVAL"})
    return order


@durable_step
def send_approval_email(ctx: StepContext, order: dict, callback_id: str) -> str:
    approve = f"{APPROVE_URL}?cb={callback_id}&decision=approve"
    reject = f"{APPROVE_URL}?cb={callback_id}&decision=reject"
    to = order.get("customer_email") or SENDER
    ses.send_email(
        Source=SENDER,
        Destination={"ToAddresses": [to]},
        Message={
            "Subject": {"Data": f"Approve order {order['order_id']}?"},
            "Body": {"Html": {"Data":
                f"<p>Order <b>{order.get('item')}</b> for ${order.get('amount')}.</p>"
                f"<p><a href='{approve}'>✅ Approve</a>&nbsp;&nbsp;"
                f"<a href='{reject}'>❌ Reject</a></p>"}},
        },
    )
    return callback_id


@durable_step
def finalize(ctx: StepContext, order_id: str, decision: str) -> dict:
    status = "APPROVED" if decision == "approve" else "REJECTED"
    ddb.Table(TABLE).update_item(
        Key={"order_id": order_id},
        UpdateExpression="SET #s = :s",
        ExpressionAttributeNames={"#s": "status"},
        ExpressionAttributeValues={":s": status},
    )
    return {"order_id": order_id, "status": status}


@durable_execution
def handler(event, context: DurableContext) -> dict:
    order = context.step(save_pending(event))

    # Create a callback and mail its id out; execution suspends at .result().
    callback = context.create_callback(
        name="order-approval",
        config=CallbackConfig(timeout=Duration.from_days(2)),
    )
    context.step(send_approval_email(order, callback.callback_id))

    result = callback.result()          # ← suspends (no compute) until /approve fires
    if isinstance(result, str):
        result = json.loads(result)
    decision = (result or {}).get("decision", "reject")

    return context.step(finalize(order["order_id"], decision))
