#!/usr/bin/env bash
# Create a test user, authenticate, and print everything test.html needs.
#
# Usage:
#   ./scripts/setup_user.sh                       # defaults: test@example.com / TestPass123!
#   EMAIL=me@x.com PASSWORD='Secret123!' ./scripts/setup_user.sh
set -euo pipefail

AWS_PROFILE="${AWS_PROFILE:-default}"
STACK="${STACK:-TenantGatewayMeteringStack}"
REGION="${AWS_REGION:-us-east-1}"
EMAIL="${EMAIL:-test@example.com}"
PASSWORD="${PASSWORD:-TestPass123!}"

out() {  # read a CloudFormation output by key
  aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

POOL_ID=$(out UserPoolId)
CLIENT_ID=$(out UserPoolClientId)
HTTP_EP=$(out EventsHttpEndpoint)
RT_EP=$(out EventsRealtimeEndpoint)
TABLE=$(out UsageTable)


aws cognito-idp update-user-pool-client \
  --user-pool-id "$POOL_ID" --client-id "$CLIENT_ID" \
  --explicit-auth-flows ALLOW_ADMIN_USER_PASSWORD_AUTH ALLOW_REFRESH_TOKEN_AUTH \
  --region "$REGION"

echo "==> Creating user $EMAIL (ignore 'already exists')"
aws cognito-idp admin-create-user \
  --user-pool-id "$POOL_ID" --username "$EMAIL" \
  --user-attributes Name=email,Value="$EMAIL" Name=email_verified,Value=true \
  --message-action SUPPRESS --region "$REGION" >/dev/null 2>&1 || true

echo "==> Setting a permanent password"
aws cognito-idp admin-set-user-password \
  --user-pool-id "$POOL_ID" --username "$EMAIL" \
  --password "$PASSWORD" --permanent --region "$REGION"

echo "==> Authenticating"
AUTH=$(aws cognito-idp admin-initiate-auth \
  --user-pool-id "$POOL_ID" --client-id "$CLIENT_ID" \
  --auth-flow ADMIN_USER_PASSWORD_AUTH \
  --auth-parameters USERNAME="$EMAIL",PASSWORD="$PASSWORD" \
  --region "$REGION")

ID_TOKEN=$(echo "$AUTH" | python3 -c 'import sys,json;print(json.load(sys.stdin)["AuthenticationResult"]["IdToken"])')
# sub = the tenant id the Lambda meters on (decode the JWT payload)
SUB=$(python3 - "$ID_TOKEN" <<'PY'
import sys, json, base64
p = sys.argv[1].split(".")[1]
p += "=" * (-len(p) % 4)
print(json.loads(base64.urlsafe_b64decode(p))["sub"])
PY
)

cat <<EOF

──────────────────────────────────────────────────────────────
 Paste these into test.html (the CONFIG block at the top):
──────────────────────────────────────────────────────────────
  HTTP_ENDPOINT : $HTTP_EP
  REALTIME_ENDPOINT: $RT_EP
  ID_TOKEN      : $ID_TOKEN
  SUB (user_id) : $SUB

 Useful:
  Usage table   : $TABLE
  Check counter :
    aws dynamodb get-item --table-name $TABLE --region $REGION \\
      --key '{"user_id":{"S":"$SUB"},"period":{"S":"$(date -u +%Y-%m)"}}'

 Note: the ID token expires in ~1 hour — re-run this script for a fresh one.
──────────────────────────────────────────────────────────────
EOF

# Also write a config file test.html can auto-load.
cat > web/config.js <<EOF
// Generated by scripts/setup_user.sh — do not commit (contains a JWT).
window.AI_GATEWAY_CONFIG = {
  HTTP_ENDPOINT: "$HTTP_EP",
  REALTIME_ENDPOINT: "$RT_EP",
  ID_TOKEN: "$ID_TOKEN",
  SUB: "$SUB"
};
EOF
echo "Wrote web/config.js — now open web/test.html in a browser."